version: '3.1'

services:
  mongo:
    build: .
    restart: always
    ports:
      - 27017:27017
    entrypoint: ["sh", "-c", "mongod --config /etc/mongod.conf & tail -f /dev/null"]
    volumes:
      - ./mongod.conf:/etc/mongod.conf
      - ./storage:/var/lib/mongodb
      
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/