version: '3.1'

services:
  mongo:
    build: .
    restart: always
    ports:
      - 27017:27017
    entrypoint: ["sh", "-c", "cp -a /tmp/keyFile /etc/keyFile \
                && chmod 400 /etc/keyFile \
                && mongod --config /etc/mongod.conf \
                && tail -f /dev/null"]
    volumes:
      - ./mongod.conf:/etc/mongod.conf
      - ./keyFile:/tmp/keyFile
      - ./storage:/var/lib/mongodb
  mongo-sec:
    build: .
    restart: always
    ports:
      - 27018:27017
    entrypoint: ["sh", "-c", "cp -a /tmp/keyFile /etc/keyFile \
                && chmod 400 /etc/keyFile \
                && mongod --config /etc/mongod.conf \
                && tail -f /dev/null"]
    volumes:
      - ./mongod-sec.conf:/etc/mongod.conf
      - ./keyFile:/tmp/keyFile
      - ./storage-sec:/var/lib/mongodb
  mongo-arb:
    build: .
    restart: always
    ports:
      - 27019:27017
    entrypoint: ["sh", "-c", "cp -a /tmp/keyFile /etc/keyFile \
                && chmod 400 /etc/keyFile \
                && mongod --config /etc/mongod.conf \
                && tail -f /dev/null"]
    volumes:
      - ./mongod-arb.conf:/etc/mongod.conf
      - ./keyFile:/tmp/keyFile
      - ./storage-arb:/var/lib/mongodb
  mongo-rs02:
    build: .
    restart: always
    ports:
      - 27117:27017
    entrypoint: ["sh", "-c", "cp -a /tmp/keyFile /etc/keyFile \
                && chmod 400 /etc/keyFile \
                && mongod --config /etc/mongod.conf \
                && tail -f /dev/null"]
    volumes:
      - ./replSet02/mongod.conf:/etc/mongod.conf
      - ./keyFile:/tmp/keyFile
      - ./replSet02/storage:/var/lib/mongodb
  mongo-sec-rs02:
    build: .
    restart: always
    ports:
      - 27118:27017
    entrypoint: ["sh", "-c", "cp -a /tmp/keyFile /etc/keyFile \
                && chmod 400 /etc/keyFile \
                && mongod --config /etc/mongod.conf \
                && tail -f /dev/null"]
    volumes:
      - ./replSet02/mongod-sec.conf:/etc/mongod.conf
      - ./keyFile:/tmp/keyFile
      - ./replSet02/storage-sec:/var/lib/mongodb
  mongo-arb-rs02:
    build: .
    restart: always
    ports:
      - 27119:27017
    entrypoint: ["sh", "-c", "cp -a /tmp/keyFile /etc/keyFile \
                && chmod 400 /etc/keyFile \
                && mongod --config /etc/mongod.conf \
                && tail -f /dev/null"]
    volumes:
      - ./replSet02/mongod-arb.conf:/etc/mongod.conf
      - ./keyFile:/tmp/keyFile
      - ./replSet02/storage-arb:/var/lib/mongodb
  mongo6:
    image: mongo:6.0.4-jammy
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27027:27017
    entrypoint: ["sh", "-c", "mongod --config /etc/mongod.conf \
                & tail -f /dev/null"]
    volumes:
      - ./mongod6.conf:/etc/mongod.conf
      - ./storage2:/var/lib/mongodb
  #mongo-express:
  #  image: mongo-express
  #  restart: always
  #  ports:
  #    - 8081:8081
  #  environment:
  #    ME_CONFIG_MONGODB_ADMINUSERNAME: admin
  #    ME_CONFIG_MONGODB_ADMINPASSWORD: password
  #    ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
